name: Update jsDelivr CDN

on:
  push:
    branches:
      - main

jobs:
  update-cdn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update CDN link
        run: |
          curl -X PURGE https://cdn.jsdelivr.net/gh/Dinkeres/jstest@main/snake.js
