name: Update CDN Link

on:
  push:
    branches:
      - main

jobs:
  update-cdn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update CDN link
        run: |
          curl -X POST \
          https://api.jsdelivr.com/v1/package/gh/Dinkeres/jstest \
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'Content-Type: application/json' \
          -d '{"files":["snake.js"]}'
